-- Seed Data for BI Dashboard

-- 1. Seed Demo User (Password: password123, pre-hashed using bcrypt)
INSERT INTO users (email, password_hash, full_name, role)
VALUES (
    'demo@bidashboard.com',
    '$2a$10$wN9aWf.qWwz/T.lU7W/NeeU/lD3/5a5E9bS3eWJ.oGvP8P8Ea2H5u', -- bcrypt hash of 'password123'
    'Demo User',
    'admin'
) ON CONFLICT (email) DO NOTHING;

-- 2. Seed Default KPIs
INSERT INTO kpis (name, target, actual, unit, status, threshold_warning, threshold_critical, description)
VALUES 
('Monthly Recurring Revenue (MRR)', 150000.00, 142500.00, '$', 'On Track', 135000.00, 112500.00, 'Total predictable revenue generated by customers in a active month.'),
('Customer Acquisition Cost (CAC)', 150.00, 168.50, '$', 'Warning', 160.00, 185.00, 'Average cost to acquire a single customer.'),
('Conversion Rate', 4.50, 4.82, '%', 'On Track', 4.00, 3.20, 'Percentage of website visitors who convert into signups.'),
('Daily Active Users (DAU)', 25000.00, 18450.00, 'qty', 'Critical', 22000.00, 19000.00, 'Number of unique users interacting with the application daily.'),
('Net Promoter Score (NPS)', 75.00, 78.00, 'qty', 'On Track', 70.00, 60.00, 'Customer satisfaction index gauging loyalty and referral likelihood.')
ON CONFLICT DO NOTHING;

-- 3. Seed Default Datasets
INSERT INTO datasets (id, name, file_name, file_size, row_count, user_id)
VALUES (1, 'Q1 SaaS Metrics', 'q1_metrics.csv', 10485, 90, 1)
ON CONFLICT (id) DO NOTHING;

-- 4. Seed Datapoints (Q1 2026 SaaS Metrics - 90 Days)
-- Inserting aggregated/representative datapoints for daily trend visualization
INSERT INTO datapoints (dataset_id, date, category, segment, revenue, sales, signups, conversion_rate)
VALUES
(1, '2026-03-01', 'Software', 'Enterprise', 4500.00, 12, 140, 2.30),
(1, '2026-03-01', 'Consulting', 'SMB', 1200.00, 3, 45, 1.80),
(1, '2026-03-02', 'Software', 'Enterprise', 4800.00, 15, 155, 2.45),
(1, '2026-03-02', 'Consulting', 'SMB', 1400.00, 4, 48, 1.95),
(1, '2026-03-03', 'Software', 'Enterprise', 5200.00, 18, 168, 2.60),
(1, '2026-03-03', 'Consulting', 'Consumer', 900.00, 90, 450, 3.10),
(1, '2026-03-04', 'Software', 'Enterprise', 4900.00, 14, 150, 2.35),
(1, '2026-03-04', 'Consulting', 'SMB', 1100.00, 3, 40, 1.75),
(1, '2026-03-05', 'Software', 'Enterprise', 5100.00, 16, 162, 2.50),
(1, '2026-03-05', 'Consulting', 'Consumer', 950.00, 95, 475, 3.25),
(1, '2026-03-06', 'Software', 'Enterprise', 5500.00, 20, 180, 2.80),
(1, '2026-03-06', 'Consulting', 'SMB', 1300.00, 4, 52, 2.10),
(1, '2026-03-07', 'Software', 'Enterprise', 5800.00, 22, 195, 2.95),
(1, '2026-03-07', 'Consulting', 'Consumer', 1050.00, 105, 520, 3.50),
(1, '2026-03-08', 'Software', 'Enterprise', 4600.00, 13, 142, 2.31),
(1, '2026-03-08', 'Consulting', 'SMB', 1150.00, 3, 42, 1.81),
(1, '2026-03-09', 'Software', 'Enterprise', 4950.00, 15, 158, 2.48),
(1, '2026-03-09', 'Consulting', 'SMB', 1350.00, 4, 49, 1.98),
(1, '2026-03-10', 'Software', 'Enterprise', 5350.00, 19, 172, 2.65),
(1, '2026-03-10', 'Consulting', 'Consumer', 920.00, 92, 460, 3.15),
(1, '2026-03-11', 'Software', 'Enterprise', 5050.00, 15, 154, 2.39),
(1, '2026-03-11', 'Consulting', 'SMB', 1120.00, 3, 41, 1.78),
(1, '2026-03-12', 'Software', 'Enterprise', 5250.00, 17, 166, 2.54),
(1, '2026-03-12', 'Consulting', 'Consumer', 980.00, 98, 485, 3.30),
(1, '2026-03-13', 'Software', 'Enterprise', 5650.00, 21, 185, 2.85),
(1, '2026-03-13', 'Consulting', 'SMB', 1320.00, 4, 53, 2.12),
(1, '2026-03-14', 'Software', 'Enterprise', 5950.00, 23, 200, 3.01),
(1, '2026-03-14', 'Consulting', 'Consumer', 1080.00, 108, 535, 3.55),
(1, '2026-03-15', 'Software', 'Enterprise', 6200.00, 25, 210, 3.20),
(1, '2026-03-15', 'Consulting', 'SMB', 1500.00, 5, 60, 2.40);
